if (MSVC)
    set(AWL_VISUALIZERS ${AWL_ROOT_DIR}/Ide/VisualStudio/Awl.natvis)

    if (EXISTS ${AWL_VISUALIZERS})
        #set_property(TARGET ${PROJECT_NAME} PROPERTY VS_DEBUGGER_VISUALIZERS ${AWL_VISUALIZERS})
        set_property(TARGET ${PROJECT_NAME} APPEND PROPERTY VS_DEBUGGER_VISUALIZERS ${AWL_VISUALIZERS_NATIVE})
        target_sources(${PROJECT_NAME} PRIVATE ${AWL_VISUALIZERS})
        set_source_files_properties(${AWL_VISUALIZERS} PROPERTIES HEADER_FILE_ONLY TRUE VS_TOOL_OVERRIDE "Natvis")
        target_link_options(${PROJECT_NAME} PRIVATE "/NATVIS:${AWL_VISUALIZERS}")
    else()
        message(WARNING "MS Visual Studio visualizer file not found: ${AWL_VISUALIZERS}")
    endif()
endif()
