if (WIN32)
    set(AWL_PLATFORM_DIR ${AWL_ROOT_DIR}/Platforms/Windows)
    target_compile_definitions(${PROJECT_NAME} PRIVATE _WIN32_WINNT=0x0A00)
    message(STATUS "Win32 native platform.")
elseif (UNIX)
    set(AWL_PLATFORM_DIR ${AWL_ROOT_DIR}/Platforms/Posix)
    message(STATUS "Posix native platform.")
else()
    message(STATUS "No native platform support.")
endif()

if (DEFINED AWL_PLATFORM_DIR)
    message(STATUS "AWL_PLATFORM_DIR: ${AWL_PLATFORM_DIR}")
    target_include_directories(${PROJECT_NAME} PRIVATE ${AWL_PLATFORM_DIR})
    file(GLOB_RECURSE AWL_PLATFORM_FILES ${AWL_PLATFORM_DIR}/*.h ${AWL_PLATFORM_DIR}/*.cpp)
    target_sources(${PROJECT_NAME} PRIVATE ${AWL_PLATFORM_FILES})
    if (AWL_COMPILE_TESTS)
        file(GLOB_RECURSE AWL_PLATFORM_TEST_FILES ${AWL_ROOT_DIR}/PlatformTests/*.h ${AWL_ROOT_DIR}/PlatformTests/*.cpp)
        target_sources(${PROJECT_NAME} PRIVATE ${AWL_PLATFORM_TEST_FILES})
    endif()
endif()
