message(STATUS "Using OpenSSL.")
if (ANDROID)
    if(NOT AWL_ANDROID_OPENSSL_DIR)
        message(FATAL_ERROR "AWL_ANDROID_OPENSSL_DIR is not set. Add -DAWL_ANDROID_OPENSSL_DIR:STRING=C:/dev/libs/android_openssl.")
    endif()
    message(STATUS "AWL_ANDROID_OPENSSL_DIR: ${AWL_ANDROID_OPENSSL_DIR}")
    include(${AWL_ANDROID_OPENSSL_DIR}/CMakeLists.txt)
else()
    find_package(OpenSSL REQUIRED Crypto SSL REQUIRED)
    message(STATUS "OpenSSL include: ${OPENSSL_INCLUDE_DIR}")
    target_compile_definitions(${PROJECT_NAME} PRIVATE AWL_OPENSSL)
    include_directories(${OPENSSL_INCLUDE_DIR})
    target_link_libraries(${PROJECT_NAME} PRIVATE OpenSSL::Crypto OpenSSL::SSL)
endif()
