include_guard(GLOBAL)

# Apply development flags to an explicit target, without changing its public API.
function(awl_apply_compiler_options target)
    set(PROJECT_NAME "${target}")
    include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/AwlCompilerOptions.cmake")
    if(MSVC AND AWL_STATIC_RUNTIME)
        set_property(TARGET ${target} PROPERTY MSVC_RUNTIME_LIBRARY
            "MultiThreaded$<$<CONFIG:Debug>:Debug>")
    endif()
endfunction()

function(awl_add_libraries)
    set(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/..")
    cmake_path(NORMAL_PATH root)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS "20.0.0")
        set(AWL_JTHREAD_EXTRAS ON)
    endif()
    # A build tree has one AWL configuration. Per-consumer MAIN/TESTS are separate.
    set(configuration "${root}")
    foreach(setting AWL_FIND_BOOST AWL_FIND_OPENSSL AWL_FIND_QT AWL_STATIC_RUNTIME
            AWL_ANSI_CMD_CHAR AWL_JTHREAD_EXTRAS AWL_DEBUG_IMMUTABLE
            AWL_HAS_STD_MOVE_ONLY_FUNCTION AWL_SANITIZE_THREAD
            AWL_SANITIZE_UNDEFINED AWL_SANITIZE_ADDRESS)
        if(${setting})
            string(APPEND configuration ";${setting}=ON")
        else()
            string(APPEND configuration ";${setting}=OFF")
        endif()
    endforeach()
    if(TARGET AWL::Core)
        get_property(existing GLOBAL PROPERTY AWL_CONFIGURATION)
        if(NOT configuration STREQUAL existing)
            message(FATAL_ERROR "AWL configuration differs between consumers. Configure AWL once before adding them.\nExisting: ${existing}\nRequested: ${configuration}")
        endif()
        return()
    endif()
    set_property(GLOBAL PROPERTY AWL_CONFIGURATION "${configuration}")

    add_library(AwlOptions INTERFACE)
    add_library(AWL::Options ALIAS AwlOptions)
    target_compile_features(AwlOptions INTERFACE cxx_std_23)
    target_include_directories(AwlOptions INTERFACE "${root}")
    if(MSVC)
        target_compile_definitions(AwlOptions INTERFACE _UNICODE NOMINMAX)
    else()
        target_compile_definitions(AwlOptions INTERFACE AWL_THREAD_ID_FORMATTER)
        if(CMAKE_SIZEOF_VOID_P EQUAL 8)
            target_compile_definitions(AwlOptions INTERFACE AWL_INT_128)
        endif()
    endif()
    foreach(definition AWL_ANSI_CMD_CHAR AWL_DEBUG_IMMUTABLE AWL_JTHREAD_EXTRAS)
        if(${definition})
            target_compile_definitions(AwlOptions INTERFACE ${definition})
        endif()
    endforeach()
    if(AWL_JTHREAD_EXTRAS)
        target_include_directories(AwlOptions INTERFACE "${root}/Extras/JThread")
    endif()
    # Sanitizer/runtime linking requirements must reach executables too.
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        if(AWL_STATIC_RUNTIME)
            target_link_options(AwlOptions INTERFACE -static-libgcc -static-libstdc++)
        endif()
        foreach(sanitizer THREAD UNDEFINED ADDRESS)
            if(AWL_SANITIZE_${sanitizer})
                string(TOLOWER "${sanitizer}" sanitizer_name)
                target_compile_options(AwlOptions INTERFACE
                    -fsanitize=${sanitizer_name} -fno-omit-frame-pointer)
                target_link_options(AwlOptions INTERFACE -fsanitize=${sanitizer_name})
            endif()
        endforeach()
    endif()
    find_package(Threads REQUIRED)
    target_link_libraries(AwlOptions INTERFACE Threads::Threads)
    if(WIN32)
        set(platform "${root}/Platforms/Windows")
        target_compile_definitions(AwlOptions INTERFACE _WIN32_WINNT=0x0A00)
    elseif(UNIX)
        set(platform "${root}/Platforms/Posix")
    endif()
    if(DEFINED platform)
        target_include_directories(AwlOptions INTERFACE "${platform}")
    endif()
    if(AWL_FIND_BOOST)
        if(POLICY CMP0167)
            cmake_policy(SET CMP0167 NEW)
        endif()
        set(Boost_USE_STATIC_LIBS ON)
        set(Boost_USE_MULTITHREADED ON)
        set(Boost_USE_STATIC_RUNTIME ${AWL_STATIC_RUNTIME})
        find_package(Boost COMPONENTS atomic thread container exception REQUIRED)
        # Unicode conversion uses Boost.Locale's header-only UTF utilities.
        target_compile_definitions(AwlOptions INTERFACE AWL_BOOST BOOST_JSON_NO_LIB BOOST_LOCALE_NO_LIB)
        target_include_directories(AwlOptions INTERFACE "${root}/Extras/Boost")
        target_link_libraries(AwlOptions INTERFACE Boost::headers
            Boost::atomic Boost::thread Boost::container Boost::exception)
        if(WIN32)
            target_link_libraries(AwlOptions INTERFACE crypt32 ws2_32)
        elseif(UNIX)
            target_compile_definitions(AwlOptions INTERFACE BOOST_ASIO_HAS_IO_URING)
            find_library(URING_LIB uring REQUIRED)
            target_link_libraries(AwlOptions INTERFACE "${URING_LIB}")
        endif()
    endif()
    if(AWL_FIND_OPENSSL)
        if(ANDROID)
            if(NOT AWL_ANDROID_OPENSSL_DIR)
                message(FATAL_ERROR "AWL_ANDROID_OPENSSL_DIR is required on Android")
            endif()
            include("${AWL_ANDROID_OPENSSL_DIR}/CMakeLists.txt")
        else()
            find_package(OpenSSL REQUIRED COMPONENTS Crypto SSL)
            target_link_libraries(AwlOptions INTERFACE OpenSSL::Crypto OpenSSL::SSL)
        endif()
        target_compile_definitions(AwlOptions INTERFACE AWL_OPENSSL)
    endif()
    if(AWL_FIND_QT)
        find_package(Qt6 REQUIRED COMPONENTS Core)
        target_compile_definitions(AwlOptions INTERFACE AWL_QT QT_NO_EMIT)
        target_include_directories(AwlOptions INTERFACE "${root}/Extras/Qt")
        target_link_libraries(AwlOptions INTERFACE Qt6::Core)
    endif()

    file(GLOB_RECURSE core_sources CONFIGURE_DEPENDS "${root}/Awl/*.cpp")
    list(FILTER core_sources EXCLUDE REGEX "/Awl/Testing/")
    if(DEFINED platform)
        file(GLOB_RECURSE platform_sources CONFIGURE_DEPENDS "${platform}/*.cpp")
        list(APPEND core_sources ${platform_sources})
    endif()
    add_library(AwlCore STATIC ${core_sources})
    add_library(AWL::Core ALIAS AwlCore)
    target_link_libraries(AwlCore PUBLIC AWL::Options)
    awl_apply_compiler_options(AwlCore)

    set(test_dependency AWL::Core)
    if(AWL_FIND_BOOST)
        file(GLOB_RECURSE boost_sources CONFIGURE_DEPENDS
            "${root}/Extras/Boost/BoostExtras/*.cpp")
        add_library(AwlBoost STATIC ${boost_sources})
        add_library(AWL::Boost ALIAS AwlBoost)
        target_link_libraries(AwlBoost PUBLIC AWL::Core)
        awl_apply_compiler_options(AwlBoost)
        set(test_dependency AWL::Boost)
    endif()
    if(AWL_FIND_QT)
        file(GLOB_RECURSE qt_sources CONFIGURE_DEPENDS
            "${root}/Extras/Qt/QtExtras/*.cpp")
        add_library(AwlQt STATIC ${qt_sources})
        add_library(AWL::Qt ALIAS AwlQt)
        target_link_libraries(AwlQt PUBLIC ${test_dependency})
        awl_apply_compiler_options(AwlQt)
        set(test_dependency AWL::Qt)
    endif()
    file(GLOB testing_sources CONFIGURE_DEPENDS "${root}/Awl/Testing/*.cpp")
    add_library(AwlTesting STATIC EXCLUDE_FROM_ALL ${testing_sources})
    add_library(AWL::Testing ALIAS AwlTesting)
    target_link_libraries(AwlTesting PUBLIC ${test_dependency})
    awl_apply_compiler_options(AwlTesting)

    add_library(AwlTestMain STATIC EXCLUDE_FROM_ALL "${root}/Main/main.cpp")
    add_library(AWL::TestMain ALIAS AwlTestMain)
    target_link_libraries(AwlTestMain PUBLIC AWL::Testing)
    awl_apply_compiler_options(AwlTestMain)
endfunction()

function(awl_add_test_sources target)
    set(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/..")
    cmake_path(NORMAL_PATH root)
    file(GLOB_RECURSE test_sources CONFIGURE_DEPENDS "${root}/Tests/*.cpp")
    if(NOT AWL_HAS_STD_MOVE_ONLY_FUNCTION)
        list(REMOVE_ITEM test_sources "${root}/Tests/EquatableFunctionTest.cpp"
            "${root}/Tests/SignalAwaitableTest.cpp" "${root}/Tests/SignalTest.cpp")
    endif()
    if(WIN32 OR UNIX)
        file(GLOB_RECURSE platform_tests CONFIGURE_DEPENDS "${root}/PlatformTests/*.cpp")
        list(APPEND test_sources ${platform_tests})
    endif()
    foreach(extra Boost Qt)
        string(TOUPPER "${extra}" extra_option)
        if(AWL_FIND_${extra_option})
            file(GLOB_RECURSE extra_tests CONFIGURE_DEPENDS "${root}/Extras/${extra}/Tests/*.cpp")
            list(APPEND test_sources ${extra_tests})
        endif()
    endforeach()
    # Registration-only translation units must be executable sources, not archives.
    target_sources(${target} PRIVATE ${test_sources})
    target_link_libraries(${target} PRIVATE AWL::Testing)
endfunction()

function(awl_link target)
    awl_add_libraries()
    get_target_property(type ${target} TYPE)
    if(type STREQUAL "INTERFACE_LIBRARY")
        set(scope INTERFACE)
    elseif(type STREQUAL "EXECUTABLE")
        set(scope PRIVATE)
    else()
        set(scope PUBLIC)
    endif()
    target_link_libraries(${target} ${scope} AWL::Core)
    if(AWL_FIND_BOOST)
        target_link_libraries(${target} ${scope} AWL::Boost)
    endif()
    if(AWL_FIND_QT)
        target_link_libraries(${target} ${scope} AWL::Qt)
    endif()
    if(NOT type STREQUAL "INTERFACE_LIBRARY")
        awl_apply_compiler_options(${target})
        if(AWL_COMPILE_TESTS)
            awl_add_test_sources(${target})
        endif()
        if(AWL_COMPILE_MAIN)
            target_link_libraries(${target} PRIVATE AWL::TestMain)
        endif()
        set(PROJECT_NAME "${target}")
        set(AWL_ROOT_DIR "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/..")
        include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/AwlIdeSupport.cmake")
    endif()
endfunction()
